Update SSL failure guidance for conda
The corporate firewall interferes with the certificate chain because it
is self-signed. Opening the failed URL in a browser allows the firewall
to process and accept the site. The interference then stops for a
limited time, so this work-around needs repitition.

```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_ser ver_certificate', 'certificate verify failed')],)",),),)
```